version: '3.8'
services:
  discord_bot:
    build: .
    container_name: discord_bot_container
    restart: unless-stopped
    environment:
      - DISCORD_BOT_APIKEY= ${DISCORD_BOT_APIKEY}
      - BOT_SEND_CHENNEL_ID= ${BOT_SEND_CHENNEL_ID}
    volumes:
      - ./data:/app/data # 持久化資料儲存位置
    networks:
      - bot_network

networks:
  bot_network:
    name: bot_network
    driver: bridge